// flow-typed signature: 58fbbd83b85ab33504762c6349bd1069
// flow-typed version: <<STUB>>/karma-edge-launcher_v^0.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-edge-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-edge-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-edge-launcher/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-edge-launcher/test/launcher.spec' {
  declare module.exports: any;
}

declare module 'karma-edge-launcher/test/mocha-globals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-edge-launcher/gruntfile.js' {
  declare module.exports: $Exports<'karma-edge-launcher/gruntfile'>;
}
declare module 'karma-edge-launcher/index' {
  declare module.exports: $Exports<'karma-edge-launcher'>;
}
declare module 'karma-edge-launcher/index.js' {
  declare module.exports: $Exports<'karma-edge-launcher'>;
}
declare module 'karma-edge-launcher/test/launcher.spec.js' {
  declare module.exports: $Exports<'karma-edge-launcher/test/launcher.spec'>;
}
declare module 'karma-edge-launcher/test/mocha-globals.js' {
  declare module.exports: $Exports<'karma-edge-launcher/test/mocha-globals'>;
}
