// flow-typed signature: 8ed8c75fc17366616c2a2ab0899c23cb
// flow-typed version: <<STUB>>/karma-opera-launcher_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-opera-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-opera-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-opera-launcher/gruntfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-opera-launcher/gruntfile.js' {
  declare module.exports: $Exports<'karma-opera-launcher/gruntfile'>;
}
declare module 'karma-opera-launcher/index' {
  declare module.exports: $Exports<'karma-opera-launcher'>;
}
declare module 'karma-opera-launcher/index.js' {
  declare module.exports: $Exports<'karma-opera-launcher'>;
}
