// flow-typed signature: b0061703541bb640055ff1fa85080495
// flow-typed version: <<STUB>>/karma-detect-browsers_v^2.2.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-detect-browsers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-detect-browsers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-detect-browsers/browsers/Chrome' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/ChromeCanary' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/Edge' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/Firefox' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/FirefoxAurora' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/FirefoxNightly' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/IE' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/index' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/Opera' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/Safari' {
  declare module.exports: any;
}

declare module 'karma-detect-browsers/browsers/SafariTechPreview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-detect-browsers/browsers/Chrome.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/Chrome'>;
}
declare module 'karma-detect-browsers/browsers/ChromeCanary.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/ChromeCanary'>;
}
declare module 'karma-detect-browsers/browsers/Edge.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/Edge'>;
}
declare module 'karma-detect-browsers/browsers/Firefox.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/Firefox'>;
}
declare module 'karma-detect-browsers/browsers/FirefoxAurora.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/FirefoxAurora'>;
}
declare module 'karma-detect-browsers/browsers/FirefoxNightly.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/FirefoxNightly'>;
}
declare module 'karma-detect-browsers/browsers/IE.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/IE'>;
}
declare module 'karma-detect-browsers/browsers/index.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/index'>;
}
declare module 'karma-detect-browsers/browsers/Opera.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/Opera'>;
}
declare module 'karma-detect-browsers/browsers/Safari.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/Safari'>;
}
declare module 'karma-detect-browsers/browsers/SafariTechPreview.js' {
  declare module.exports: $Exports<'karma-detect-browsers/browsers/SafariTechPreview'>;
}
declare module 'karma-detect-browsers/index' {
  declare module.exports: $Exports<'karma-detect-browsers'>;
}
declare module 'karma-detect-browsers/index.js' {
  declare module.exports: $Exports<'karma-detect-browsers'>;
}
